spring.application.name=task-api


spring.datasource.url=jdbc:mysql://10.116.64.14:13306/nhn_academy_32?useSSL=false&serverTimezone=UTC
spring.datasource.username=	nhn_academy_32
spring.datasource.password=	EJdrW!(bf]HjT9a5